// <auto-generated />
using System;
using CryptoPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511202703_DropUniquePlayerWalletAddress")]
    partial class DropUniquePlayerWalletAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("player_index_seq");

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coin");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_balances");

                    b.HasIndex("PlayerId", "Coin", "Chain")
                        .IsUnique()
                        .HasDatabaseName("ix_balances_player_id_coin_chain");

                    b.ToTable("balances", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coin");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer")
                        .HasColumnName("confirmations");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime?>("CreditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("credited_at");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("FromAddress")
                        .HasColumnType("text")
                        .HasColumnName("from_address");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_address");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_deposits");

                    b.HasIndex("TxHash")
                        .IsUnique()
                        .HasDatabaseName("ix_deposits_tx_hash");

                    b.ToTable("deposits", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("balance_before");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_players_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_players_username");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.PlayerWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_player_wallets");

                    b.HasIndex("Address")
                        .HasDatabaseName("ix_player_wallets_address");

                    b.HasIndex("PlayerId", "Coin", "Chain")
                        .IsUnique()
                        .HasDatabaseName("ix_player_wallets_player_id_coin_chain");

                    b.ToTable("player_wallets", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.WalletKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChainGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain_group");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_private_key");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_keys");

                    b.HasIndex("PlayerId", "ChainGroup")
                        .IsUnique()
                        .HasDatabaseName("ix_wallet_keys_player_id_chain_group");

                    b.ToTable("wallet_keys", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.Withdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coin");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("Fee")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("fee");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_address");

                    b.Property<string>("TxHash")
                        .HasColumnType("text")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_withdrawals");

                    b.ToTable("withdrawals", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.Balance", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.Player", "Player")
                        .WithMany("Balances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_balances_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.PlayerWallet", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.Player", "Player")
                        .WithMany("Wallets")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_wallets_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.WalletKey", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_keys_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.Player", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
